### ISSUE TITLE
Can we use Doxygen to generate the code documentation?

### ISSUE THREAD

**Issue by KazeSenshi** [HouraiTeahouse/FantasyCrescendo#10]
Hello guys, can we use [Doxygen](https://github.com/doxygen/doxygen) to create the documentation about the project's code? It is useful to understand some functions and modules from the system and it is pretty famous, being used by a lot of great softwares like the [PostgreSQL database with a huge source code](http://doxygen.postgresql.org/files.html).

Then we could release a Doxygen about the project in each game's new version release or do some [black magic](http://rickfoosusa.blogspot.com.br/2011/10/howto-use-doxygen-with-github.html) to let it create the documentation automagically.

Unity3d's Monodevelop supports natively the documentation syntax used by Doxygen, you just need to type '///' before a function or a variable field and the IDE will auto-complete the documentation fields, letting you type the details. 

For example here is the header from one function from another project mine.
```
	/// <summary>
	/// D-Engine function. It takes the universe and using the planner passed in 
	/// the constructor and its status through the determined time window.
	/// If S is the simulated time, then t0 <= S < t0 + deltaT. If you want to continue
	/// the simulation, for example, you can call this function again using t0 = t0+deltaT.
	/// </summary>
	/// <param name="t0">The initial time.</param>
	/// <param name="deltaT">The maximum time length.</param>
	/// <returns><c>true</c>, if the result desired by the planner is satisfied, <c>false</c> otherwise.</returns>
	/// <seealso cref="ExternalPlanner::getResult"/>
	public bool dEngine ( float t0, float deltaT ) {	
                  ....
      }
```

**Comment by james7132** [comment]
Indeed, I have looked into  it since you first mentioned it in the reddit comment.

It would definitely be helpful to have some proper documentation of the code (As there currently is none).

The idea to use it with Github pages is a great one. I originally was thinking of putting a dev blog there, but this may work even better for the purposes of development.

**Comment by KazeSenshi** [comment]
Even without the plugin we could use a GUI-based documentation generator. The most important thing for now is to say to any contributor to follow its syntax. When I have time I'll document better my code.
