### ISSUE TITLE
Switching to AssetBundles broke Stage Loading

### ISSUE THREAD

**Issue by abyll** [HouraiTeahouse/FantasyCrescendo#113]
The new SceneLoader.LoadScene function call defaults to Single loadscenemode; it should be Additive in order for the Bootstrap scene to load into a stage.

The PlayerManager doesn't load the test Character or Player now. This could be because the youmu_konpaku.asset isn't correctly referenced. (Guessing from an editor error - "This game cannot find this Character Data if it is not in a Resources folder. Please move it to a Resources (sub)folder.")

**Comment by james7132** [comment]
Fixed as of 51f45e3d1c567d7fb1e703f1fb664d77c01ee70b
