### ISSUE TITLE
Fog appears globally insted of height-fog

### ISSUE THREAD

**Issue by Gabo-7** [HouraiTeahouse/FantasyCrescendo#122]
- Fantasy Crescendo Version: Build #220
- Operating System: Win10
- Expected Behavior: Height fog
- Actual Behavior: Global fog

![image](https://cloud.githubusercontent.com/assets/18556581/26085265/8029d236-39a8-11e7-8853-4f0d7f203ead.png)

**Comment by james7132** [comment]
This seems to be caused by an improperly built shader during the asset bundle build process. The logs from Unity Cloud Build has a few warnings about it, I'll see if I can resolve them.

**Comment by james7132** [comment]
@Gabo-7: can you still reproduce this with the latest build on from the launcher? I cannot seem to reproduce this in any build or environment.

**Comment by james7132** [comment]
As discussed on Discord, this seems to be resolved.
