### ISSUE TITLE
Running while in the falling animation causes animation to stop upon landing

### ISSUE THREAD

**Issue by Mimars-Project** [HouraiTeahouse/FantasyCrescendo#126]
- Fantasy Crescendo Version: Latest Version (?)
- Operating System: Windows 8.1
- Expected Behavior: Running animation
- Actual Behavior: Single frame
- Steps to reproduce the behavior:
Jump and fall to trigger falling animation. 
While in falling animation, press A or D to run. 
When the character lands while running, the animation becomes frozen as in the picture.
Turning direction during the frozen animation continues the frozen animation.
(The character will keep running but the animation is frozen during the time the character is running)

Other helpful information:
Walking does not trigger this.
If the character is in a different animation, this is not triggered.
Any other action, other than A or D, will stop the frozen animation.

[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1050794/output_log.txt)
![screenshot-06-04-2017-233419](https://cloud.githubusercontent.com/assets/29160537/26766345/f9a33508-49e3-11e7-9276-593a92d9c7be.png)

**Comment by james7132** [comment]
@Mimars-Project can you still replicate this behavior in the most recent build?

**Comment by Mimars-Project** [comment]
Seems to work fine now
