### ISSUE TITLE
Lack of normal maps and shaders on lower end hardware

### ISSUE THREAD

**Issue by spaztron64** [HouraiTeahouse/FantasyCrescendo#127]
- Fantasy Crescendo Version: Development Build 220
- Operating System: Microsoft Windows 7 build 7601 x64
- Expected Behavior: http://i.imgur.com/wvbtyo4.png
- Actual Behavior: http://i.imgur.com/v6uafEZ.png
- Steps to reproduce the behavior:
  Use an older Graphics card. (For example, my main GPU is a Radeon HD 3470 with 256MB of RAM)

Log file:https://comfy.moe/gkdrok.txt

**Comment by james7132** [comment]
Seems to be a main issue with the terrain, the trees and mushrooms are rendering fine.

**Comment by james7132** [comment]
Looking at the logs:
```
D3D shader create error for vertex shader [0x80070057]
D3D shader create error for pixel shader [0x80070057]
D3D shader create error for vertex shader [0x80070057]
D3D shader create error for pixel shader [0x80070057]
D3D shader create error for geometry shader [0x80070057]
D3D shader create error for vertex shader [0x80070057]
D3D shader create error for pixel shader [0x80070057]
D3D shader create error for geometry shader [0x80070057]
```

This likely is the cause. Looks like it's a Unity side issue. Can you file a bug report with them?

**Comment by james7132** [comment]
This seems to be a vanishing case given that Unity has announced deprecation and eventual removal of DX9 support. Marking closed for now and bumping up minimum requirements to DX11.
