### ISSUE TITLE
Characters shouldn't go through the Dash->Run->RunBrake cycle if directional input is held for less than the minimum dash length.

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#150]
- Fantasy Crescendo Version: Development build #251
- Operating System: Windows 10
- Expected Behavior: A hard (smash) horizontal directional input will put a character into a dash, which resolves into run if the directional input is held down for the time it takes to travel the minimum dash length.  If the input is held down for shorter, the character should return to an Idle state after traveling the minimum dash length.
- Actual Behavior: Character transitions from Idle->Dash->Run->RunBrake->Idle regardless of length of dash input.
- Steps to reproduce the behavior:
  0. Load game, any stage, console, put character on the ground.
  0. Make a smash directional input.
- \(optional) Possible solution/fix/workaround - don't think this necessarily needs to be animated, but if it looks strange maybe a blend here would be ok.

Other helpful information:
- Attach the relevant `output_log.txt` in the `fc_Data` folder.
[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1089668/output_log.txt)

**Comment by james7132** [comment]
What would be the expected state transition? Idle -> Dash -> Idle?

**Comment by pzhang87** [comment]
95% certain it's Idle->Dash->Idle.

**Comment by james7132** [comment]
OK then, would a transition from Dash to Idle if the movement input is not adequate at the end of the Dash state work in this case? This would set the minimum dash distance to the distance covered by the Dash state, while letting characters to continue to run if they continue to hold the input.

**Comment by pzhang87** [comment]
I believe this should be OK
