### ISSUE TITLE
Weird ledge behavior when trying to climb back up

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#152]
### When reporting a bug/issue:
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit #252
- Operating System: Windows 10 64-bit
- Expected Behavior: Character should climb or jump ledge.  (I think a diagonal input should place priority on jumping).
- Actual Behavior: https://youtu.be/-yJC2CH3ZM8
- Steps to reproduce the behavior:
  0. Get character to grab ledge.
  0. While holding the ledge, press/hold up+towards the stage. 
- \(optional) Possible solution/fix/workaround

Other helpful information:
- Attach the relevant `output_log.txt` in the `fc_Data` folder.
[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1090379/output_log.txt)

**Comment by james7132** [comment]
Seems like we'll need to implement the actual ledge climb animation with root motion to fix this.
