### ISSUE TITLE
Character doesn't seem to be transitioning into AerialJump state when using midair jump

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#154]
### When reporting a bug/issue:
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit #252
- Operating System: Windows 10 64-bit
- Expected Behavior: Character state should show Fall->AerialJump->Fall.
- Actual Behavior: Doesn't show this behavior.
- Steps to reproduce the behavior:
  0. Start game on debug stage or with the console logging on.
  0. Jump, then jump again in midair.  Keep an eye on the console or the UI element tracking state changes for the expected behavior (which doesn't happen)

**Comment by james7132** [comment]
This seems to be resolved as of c62fb3bb7b750b21f6ba85e6f70418d31068093f
