### ISSUE TITLE
Delayed movement after landing

### ISSUE THREAD

**Issue by james5922** [HouraiTeahouse/FantasyCrescendo#158]
- Fantasy Crescendo Version: Build **265**
- Operating System: Windows 7
- Expected Behavior: Immediate ability to move after landing
- Actual Behavior: Delay of about 1 second between landing and regaining movement.
- Steps to reproduce the behavior:
  1: Select the "Forest of Magic" stage.
  2: Jump. Doesn't matter which kind of jump.
  3: Try to move immediately after landing.

[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1099814/output_log.txt)

**Comment by pzhang87** [comment]
Seems like this is working as intended but the landing lag time window is much too large.

**Comment by james5922** [comment]
I was getting 25 FPS at the time, if that helps with anything.

**Comment by james7132** [comment]
@pzhang87 what is a good timing relative to what we see now.

@james5922: animations should be framerate independent. Framerate shouldn't affect the actual timing.

**Comment by james5922** [comment]
Bug still occurs in Build 265.

**Comment by james7132** [comment]
As discussed on Discord, this seems to be resolved. Closing.
