### ISSUE TITLE
Inability to use [ALT]+[TAB] to switch windows while FC is running

### ISSUE THREAD

**Issue by james5922** [HouraiTeahouse/FantasyCrescendo#159]
### When reporting a bug/issue:
- Fantasy Crescendo Version: Build 255
- Operating System: Windows 7
- Expected Behavior: Cycle to next window
- Actual Behavior: Nothing
- Steps to reproduce the behavior:
  1: Open up any stage
  2: Press [ALT] + [TAB].
(Fullscreen)
[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1099819/output_log.txt)

**Comment by james7132** [comment]
I cannot seem to reproduce this on any of my machines. Does anyone else who has Windows 7 see these issues?

**Comment by james5922** [comment]
I was pressing the wrong button and I didn't realize it.
