### ISSUE TITLE
Gamepad - character doesn't jump with up directional input

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#161]
### When reporting a bug/issue:
- Fantasy Crescendo Version: 0.3.0-alpha dev build #255
- Operating System: Windows 10 64-bit
- Expected Behavior: Upward directional input on gamepad doesn't jump.
- Actual Behavior: Characters should jump with an upward directional input on gamepad.  (This should be something that you can disable as part of player preferences.)
- Steps to reproduce the behavior:
  0. After loading a stage and getting into a game while having am (Xbox) gamepad connected, press up on the left control stick.

**Comment by james7132** [comment]
This will need to have directional movement smash detection to complete. 

Also I presume we would like for this to be configurable as a controller config option, much like the "Tap Jump" option in normal smash.

**Comment by james7132** [comment]
This is dependent on #165 to be resolved first.
