### ISSUE TITLE
Aerial drift doesn't happen because character stuck in JumpStart

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#168]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #265
- Operating System: Windows 10
- Expected Behavior: After initiating a jump, a character should be able to drift left or right while in the Jump state.
- Actual Behavior: Character is locked into JumpStart for too long which prevents a character from drifting left or right while in the air.
- Steps to reproduce the behavior:
  0. When loaded in a game, dash/walk in a direction and push the jump button.

**Comment by james7132** [comment]
9ca4d56f488162d6b3fa5228af14adbfd319613a splits the existing jump animation into two parts and applies them separately to each state, as well as allowing movement in the Jump state. Does this fix the issue?

**Comment by pzhang87** [comment]
Works for now, will revisit after experimenting with different timings.  The question is if we need the ability to drift to extend into JumpStart while the character is still grounded (as some other games have it this way).  If so, I'll file another issue.

**Comment by james7132** [comment]
We can deal with that in a separate issue for now. This seems to be resolved as of now.
