### ISSUE TITLE
Implement movement states out of Shield

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#170]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #265
- Operating System: Windows 10
- Expected Behavior: When shielding, character should roll, sidestep, or jump based on the corresponding directional (and/or button) input - left/right, down, and up (or jump button) respectively.
- Actual Behavior: Character rotates when a horizontal direction is pushed; jumps when the jump button is pushed, but doesn't enter JumpStart/Jump state; does nothing when the down direction is input.

**Comment by james7132** [comment]
This has several requirements:

- [ ] Add state transitions for these states
- [ ] Create animations for these states
- [ ] Add fixed and forced movement as a part of the states

The former two can be easily done, but the latter requires engine extension for supporting this.

**Comment by james7132** [comment]
Movement and transitions are done. We are now blocked by animations to complete this.
