### ISSUE TITLE
Shield should not recover if the player hits the shield button again after a certain amount of time. 

### ISSUE THREAD

**Issue by GoldenDrummer730** [HouraiTeahouse/FantasyCrescendo#175]
Suppose the player decides to shield after say 1 second of already hitting the shield button,
the shield could stay where it was rather than recover. That way you can more or less penalize people for spamming the shield button as they get closer to the stun period. 

Now if the shield is tapped and then tapped within < 1 second then the shield can stay at it's max value btu this is only when the shield is at max. 

Feature Request.

**Comment by james7132** [comment]
Implemented as of 7e1f05640f06e1b0354f5176ab4887243fe17b51
