### ISSUE TITLE
Shielding appears to be broken.

### ISSUE THREAD

**Issue by james5922** [HouraiTeahouse/FantasyCrescendo#178]
- Fantasy Crescendo Version: Build #271
- Operating System: Windows 7
- Expected Behavior: Shielding.
- Actual Behavior: Second jump of double jump triggered.
- Steps to reproduce the behavior:
  0. Press [L-Shift].

Other helpful information: 2 different sources.
[Video (Gabo7)](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1143338/2017-07-12-1558-25.zip)
[Output log (James5922)](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1143347/output_log.txt)

**Comment by james7132** [comment]
I cannot seem to replicate this in build #273 or later. Does this seem to be fixed?

**Comment by james5922** [comment]
Nope.
[Build #276](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1144779/2017-07-13.06-11-03.zip) still bugs.

**Comment by james7132** [comment]
Confirmed to be fixed in build #416.
