### ISSUE TITLE
Pressing S causes the character to jump

### ISSUE THREAD

**Issue by Mimars-Project** [HouraiTeahouse/FantasyCrescendo#184]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #275
- Operating System: Windows 8.1
- Expected Behavior: Pressing S crouches the character
- Actual Behavior: Pressing S causes the character to jump slightly
Holding S causes the character to hop repeatedly

**Comment by james7132** [comment]
0305db6874e10f1803e63e15eb1ef17cdbda9377 should resolve this.
