### ISSUE TITLE
Holding W while on the ground makes the character unable to move

### ISSUE THREAD

**Issue by Mimars-Project** [HouraiTeahouse/FantasyCrescendo#185]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #275
- Operating System: Windows 8.1
- Expected Behavior: Nothing
- Actual Behavior: Unable to move using either A D 'Left Arrow' or 'Right Arrow
- Steps to reproduce the behavior:
  1. Hold W and land

The movement keys (A D 'Left Arrow' or 'Right Arrow') only turn the character.

**Comment by james7132** [comment]
Can replicate this.  Not sure what this is causing this.
