### ISSUE TITLE
No Mouse Interaction

### ISSUE THREAD

**Issue by Asthmagithub** [HouraiTeahouse/FantasyCrescendo#186]
- Fantasy Crescendo Version: v.0.3.0-alpha develop-linux-universal Build#94
- Operating System: Kubuntu 17.04 (Kernel version 4.10.0-26)
- Expected Behavior: Mouse interaction with main menu works.
- Actual Behavior: Mouse interaction with menu does not work, though keyboard shortcuts do.

- Steps to reproduce the behavior:
  1. Launch the game. (in the above mentioned version of linux?)

**Comment by james7132** [comment]
As confirmed on Discord, @Asthmagithub moved off of Kubuntu as an OS. I'm going to temporarily close this until someone else brings up the issue.
