### ISSUE TITLE
Jump is broken

### ISSUE THREAD

**Issue by Gabo-7** [HouraiTeahouse/FantasyCrescendo#187]
- Expected Behavior: Jump working as it should
- Actual Behavior: Sometimes the second jump triggers even if you only pressed once. Sometimes the second jump doesn't go it's full distance. Youmu also twitches mid-air when trying to jump twice.
- Steps to reproduce the behavior:
1- Jump -> Second jump

**Comment by james7132** [comment]
As discussed on Discord, this seems to be fixed as of the last commit.
