### ISSUE TITLE
Changing stages without stopping game causes softlock 

### ISSUE THREAD

**Issue by james5922** [HouraiTeahouse/FantasyCrescendo#188]
### When reporting a bug/issue:
- Fantasy Crescendo Version: Build #276
- Operating System: Windows 7
- Expected Behavior: Proper character clearing and restarting.
- Actual Behavior: Softlock - "P1" indicator shown, but character is not loaded.
- Steps to reproduce the behavior:
  1. Enter any stage and load a character.
  2. Press Ctrl+R without unloading the character.
  3. Enter another stage.

[Output log](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1146227/output_log.txt)
![bug](https://user-images.githubusercontent.com/20325386/28181997-83a12866-67d8-11e7-9579-bca268559083.png)

**Comment by james7132** [comment]
Seems to be an issue with the NetworkManager's state not being reset after exiting the scene. Fix pending.
