### ISSUE TITLE
Game hangs indefinitely on loading screen

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#193]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #285
- Operating System: Windows 10

Console message:
>Unable to open archive file: D:/Games/FantasyCrescendo/Development/fc_Data/StreamingAssets/bundles/Windows

Output log: 
[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1149184/output_log.txt)

**Comment by james7132** [comment]
Can you affirm that that file exists? At a first glance this may be an issue with the launcher/patcher, can you try a clean installation?

**Comment by james7132** [comment]
This seems to be caused by an improperly built MeshCollider erroring out the asset bundle build process, which prevented the buliding of the AssetBundleManifest. Fixing it should fix the build.
