### ISSUE TITLE
Hosting a game before stage is selected spawns Youmu

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#194]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #286
- Operating System: Windows 10 64-bit
- Actual Behavior: See video https://www.youtube.com/watch?v=bCJkhDOmrN4
- Steps to reproduce the behavior:
  0. Launch game
  0. Press LAN Host (H)

**Comment by james7132** [comment]
This will likely be resolved when the proper scene management with networking is introduced, as this is a result of the debug network HUD that is provided.

**Comment by james7132** [comment]
This should no longer be possible as there is no longer a constant network menu open. Only on stages.
