### ISSUE TITLE
Character drifts the direction she is facing while airborne when left/right directional input is held, regardless of direction

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#195]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit build #286
- Operating System: Windows 10 64-bit
- Expected Behavior: Character should drift in the direction corresponding to the directional input while airborne (Jump, Fall, JumpAerial states)
- Actual Behavior: Character drifts in the direction she is currently facing regardless of input.  See video https://www.youtube.com/watch?v=sl1sNDkgs1g
- Steps to reproduce the behavior:
  0. Enter an airborne state, either from walking/running off of a platform or from jumping.
  0. Input direction left/right, opposite from the direction character is facing.  (If grounded, delay the directional input, character changes direction she is facing, and thus direction of jump).

**Comment by james7132** [comment]
Seems like this is still not fixed, likely due to bad state assigments. Reopening.
