### ISSUE TITLE
Soft Platforms

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/FantasyCrescendo#2]
We need a way for characters to jump up through passable platforms, as well as a way to "down jump" through similar platforms as well.

**Comment by KazeSenshi** [comment]
You could use trigger colliders to control the player's [collision layer](http://docs.unity3d.com/Manual/LayerBasedCollision.html) and ignore collisions with thin platforms.

You could check if the player is *grounded* in a collider in the layer of *thin colliders* then you could change the player's layer for some seconds to let it do the down jump.

**Comment by james7132** [comment]
Thanks to Unity's Platform Effectors. Jumping through platforms is implemented. We just need a explicit down-jump/fall through implementation.

**Comment by james7132** [comment]
After switching back from 2D to 3D physics, this issue comes back in the open. 

One possible solution that I see now is a trigger on one side that causes the movement colliders on players to ignore collision with the actual solid part of the platform.

**Comment by james7132** [comment]
Done as of yesterday.
