### ISSUE TITLE
implement hitstun

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#210]
Expected behavior is as follows:

When a character is taking a hit, they should be locked into a stunned state for a length of time before being launched - DamageStun or DamageStunAir, as exists currently.  The length of the hitstun should scale with the damage in some form - Smash does f = d/3 + 3 (rounded down, capped at 20f), where f is the duration in frames, and d is the damage in percent.  We can/should tweak this to suit our own needs.

Hitstun states also need to account for Smash DI (hitstun DI?)

**Comment by james7132** [comment]
Hitstun as an engine concept has been introduced in 954130a4ff18d535ec71d2104be220a0796ad138, where it was also introduced as a state machine parameter, and  manual movement while in hitstun was added in 448a4648c0ed23dd65138c82557feeed79197b74.

The main missing parts to this particular issue are the actual state transitions into DamageStun and DamageStunAir, and the corresponding animations. 

The feature has been tested only locally, but written to work over the network as well. We'll need to playtest whether it works well over the network. 

We have a seperate issue for hitstun DI (#211), and we should probably add a seperate issue for Smash DI. However, I think hitlag needs to be implemented fully before Smash DI has any meaningful impact on the game.

**Comment by james7132** [comment]
Done with reimplementation.
