### ISSUE TITLE
Allow binding sound effects to hitboxes

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/FantasyCrescendo#218]
This will be the easiest way to add hitsounds: attach an audio source to the hitbox object, which will automatically play when it collides with a valid object.

**Comment by pzhang87** [comment]
is there something that already handles sounds for when a move is used that doesn't necessarily collide with anything?

**Comment by james7132** [comment]
Good point. I've been considering using https://blogs.unity3d.com/2017/06/06/unity-2017-1-beta-feature-highlight-timeline-cinemachine/ to define attacks instead of simple animations. This would allow orchestrating not only animations, but virtually everything about a character.

**Comment by james7132** [comment]
Hitboxes support binding arbitrary sound and visual effects now.
