### ISSUE TITLE
Add hitlag to hits

### ISSUE THREAD

**Issue by james7132** [HouraiTeahouse/FantasyCrescendo#220]
Hitlag is defined as the brief period after being hit where both the aggressor and the defender are briefly frozen in time. This provides a stronger feeling of impact.

**Comment by pzhang87** [comment]
related to #210

**Comment by james7132** [comment]
It certainly blocks #211. #210 is blocked until tested with in-game attacks that actually damage/knockback.

**Comment by james7132** [comment]
Complete as of 0b2f2306511c433aa30e91b5c6c48f09e321ff15
