### ISSUE TITLE
GameCube controllers connected via MAYFLASH PC/Wii U Controller Adapter not supported

### ISSUE THREAD

**Issue by Leeto64** [HouraiTeahouse/FantasyCrescendo#230]
- Fantasy Crescendo version: 0.3.0-alpha
- Operating System: Windows 7 Professional Edition

Game does not react to my currently connected GameCube controller, it is connected on the Player 1 port, and can neither be used on the Menus, nor to control Youmu
Not sure about other gamepads, but GameCube controllers are quite likely the most popular for Super Smash Bros. fans, so support for this type of controller seems almost mandatory

**Comment by james7132** [comment]
This should be fixed as of a7bebf8618dbc8d133a8cb52b4f076bbd21a1049. The builds are currently broken due to a Unity Cloud Build bug. Can you please test this when the dev builds are restored?

**Comment by james7132** [comment]
As discussed on Discord, controller detection seems to work, but some buttons seem to be unusable.

**Comment by james7132** [comment]
This seems to work with the new Unity InputSystem; however the override to make it a gamepad controller doesn't seem to work. This will need the package to be updated to support overrides properly.

**Comment by james7132** [comment]
This should be added as of 6effcc34e04df94491e205eaebde7ec35eab4537
