### ISSUE TITLE
Revival Platform does not disappear immediately after Youmu leaves it - Can be jumped back to

### ISSUE THREAD

**Issue by Leeto64** [HouraiTeahouse/FantasyCrescendo#239]
- Fantasy Crescendo Version: 0.3.0 alpha (Stable)
- Operating System: Windows 7 Professional

On the Super Smash Bros. series, revival platforms (for when a character is KO'd) disappear immediately once the character leaves it, working merely as a way for players to return to the stage after a KO
On the current version, the platform stays behind even after Youmu leaves it, being possible to jump back on it.
Not tested with multiple players, nor on stages other than the Debug stage

A possible fix could be the platform instantly disappearing once Youmu stops colliding with it?

**Comment by james7132** [comment]
Done with reimplementation.
