### ISSUE TITLE
implement RunBrake and RunTurn animations

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#243]
Current build lacks these two animations.  Testing whether or not Youmu is behaving as intended in situations that trigger these states is currently difficult as it isn't apparent visually.

**Comment by james7132** [comment]
Animations for both have been created, need to be added to the repo.

**Comment by james7132** [comment]
Animations are implemented. RunTurn is broken due to badly handled state transitions.
