### ISSUE TITLE
rolls should be fixed length

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#244]
### When reporting a bug/issue:
- Fantasy Crescendo Version: v0.3.0-alpha
- Operating System: Windows 10
- Expected Behavior: After shielding, a character's roll should force movement of a fixed length.
- Actual Behavior: Character can roll a variable distance based on how long the directional input is held on controller.
- Steps to reproduce the behavior:
  0. With Youmu, while holding shield, press/hold a horizontal directional input on controller.  The length of roll appears to correspond to how long the input is held.

**Comment by james7132** [comment]
This should be fixed as of 85cb16186519024bcae553aa3989b793e1b65499
