### ISSUE TITLE
in Unity, updating the animation controller progressively takes more time

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#245]
In Unity, updating the animation controller progressively takes more time the longer Unity has been open.  This becomes problematic when trying to quickly iterate on a set of simple timing changes for different animations.

**Comment by james7132** [comment]
Hopefully the new change to using Timeline will null and void this problem by no longer requiring a animation controller.

**Comment by james7132** [comment]
This will definitely be complete when the Timeline state editor is complete.

**Comment by james7132** [comment]
This has been resolved with the new Timeline state editor.
