### ISSUE TITLE
in Unity, expose way to edit how long intangibility lasts during an escape state

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#246]
Currently, characters are intangible entirely through their rolls or sidestep.  We should have a way in Unity to define how long this intangibility lasts, and at what point this intangibility lasts for.

**Comment by james7132** [comment]
This should be resolved when the new Timeline driven state controller is completed. You should be able to alter the type of every individual hitbox at explicit times when it's done.

**Comment by james7132** [comment]
This is individually editable via the Timeline editor now.
