### ISSUE TITLE
Xbox 360 USB controller not fully supported yet

### ISSUE THREAD

**Issue by Leeto64** [HouraiTeahouse/FantasyCrescendo#252]
- Fantasy Crescendo Version: v0.3.0-Alpha Development-64 bit Build #344
- Operating System: Windows 7 Professional

While using my wired USB Xbox 360 (model X854237-001) controller, unusually, only the analog stick and "A" button work. However, running is impossible via the analog stick, and A pauses the game.
The second analog stick makes the mouse move, outside of the game, while the middle "Xbox" button makes a "help" prompt for the controller to appear, both outside of the game.

**Comment by james7132** [comment]
Can you provide the `output_log.txt` for when you play with the controller?

**Comment by Leeto64** [comment]
how do i get that?

**Comment by james7132** [comment]
It should be under `{INSTALL_DIRECTORY}/Development/fc_Data/output_log.txt`.

The install directory should be by default `C:\Games\Fantasy Crescendo\` by default.

**Comment by Leeto64** [comment]
Alright, i'm guessing this is the most recent version of the file, from the little bit i've played right now to test better a few buttons on the controller
hope it helps, if needed, i can test further with the controller

[output_log.txt](https://github.com/HouraiTeahouse/FantasyCrescendo/files/1319660/output_log.txt)

**Comment by james7132** [comment]
This should be fixed as of a7bebf8618dbc8d133a8cb52b4f076bbd21a1049. The builds are currently broken due to a Unity Cloud Build bug. Can you please test this when the dev builds are restored?
