### ISSUE TITLE
Air Jump doesn't work properly

### ISSUE THREAD

**Issue by Leeto64** [HouraiTeahouse/FantasyCrescendo#253]
- Fantasy Crescendo Version: 0.3.0-alpha-64 bit development build #344
- Operating System: Windows 7 Professional

Jumping from midair, while causing a jumping animation to occur, doesn't yet give any sort of upwards or horizontal propulsion - actually, it instead halts all horiozntal momentum Youmu has. It also doesn't seem to affect, in any way, fast-falling.

**Comment by james7132** [comment]
This should be fixed in a recent commit. Can you check if this has been fixed?
