### ISSUE TITLE
Clicking a stage select button multiple times will load the stage multiple times and crash the game

### ISSUE THREAD

**Issue by Duckus6** [HouraiTeahouse/FantasyCrescendo#257]
If my title wasn't clear I screenshotted the screen where you click the stage twice. To clarify you need to click twice before the first stage loads. I have only tested on the "Forest of Magic" stage
![image](https://user-images.githubusercontent.com/16746643/31154892-1c4bbb58-a8a2-11e7-84fe-78064df067d4.png)

- Fantasy Crescendo Version: 0.4.0 alpha
 Operating System: Windows 7 (I dont think error is OS related)
- Expected Behavior: Game loads, ignoring secondary clicks
- Actual Behavior: Game loads multiple stages which causes the game to crash
- Steps to reproduce the behavior: Click the stage on the stage selected screen again before the stage finished loading.

I am guessing this would be reproduced choosing any stage after the stage starts loading and not just the same stage so my guess for fixing it would be to disable the buttons once one has been clicked.

**Comment by james7132** [comment]
Fixed with reimplementation.
