### ISSUE TITLE
keyboard input sometimes controls both characters when multiple input sources are plugged in

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#261]
- Fantasy Crescendo Version: v0.3.0-alpha development-64-bit Build #368
- Operating System: Win10
- Expected Behavior: Keyboard input should control a single character when multiple input sources are available.
- Actual Behavior: Some keyboard input controls both characters when an XBox360 controller is plugged in.  Arrow keys will cause 2P to dash while 1P walks.  Shift will cause 2P to jump while 1P shields.

**Comment by james7132** [comment]
Done with reimplementation.
