### ISSUE TITLE
Stuck on the edge of the stage

### ISSUE THREAD

**Issue by isw766** [HouraiTeahouse/FantasyCrescendo#262]
Fantasy Crescendo Version: Build#298
Operating System: Windows 10
----------------------------------------------------------------------------
After grabbing onto the ledge, the character model becomes stuck in the grabbing position. Jumping and other actions do nothing. Trying to move causes the model to glitch up in down, but still remains in it's grabbing position and on the ledge.
![image](https://user-images.githubusercontent.com/24923031/35774586-8722fae8-0939-11e8-82cf-2ee05e0e0757.png)

**Comment by james7132** [comment]
The issue with ledge grabbing not snapping players to the ledge should be resolved. However the inputs to get out of the ledge grab state seems to still be there.

**Comment by james7132** [comment]
This should be fixed as of 509aff657df880ead08194d71eea052b34db2806
