### ISSUE TITLE
Ledge issues

### ISSUE THREAD

**Issue by magus0** [HouraiTeahouse/FantasyCrescendo#61]
Hitbox issues with the ledge
Reproduction:
 - When walking up to the ledge, will snap to ledge when on the ground
expected:
Won't snap onto edge until in the air at least
reproduction:
 - When hanging on to the ledge, while holding away from the ledge and press the up or jump button
 - character will face away from the ledge for one frame then snap back onto the ledge
expected:
Jump off the ledge in a direction away from it.

Fall off while hanging onto the ledge, no more jumps usable.
Reproduction:
 - Hang off a ledge
 - Jump and snap back onto the ledge at least once
 - Press the down, and one of the other directions a few times
 - Press the up or jump key, doesn't matter how quickly you press the direction keys before.
 - Character will fall straight down and cannot jump or move in the air.
expected:
Not to drop straight down with no control over character

**Comment by james7132** [comment]
Walking up to the ledge issue resolved.

**Comment by james7132** [comment]
All fixed as of cf048d0bcc119d378aba499c212649d022e3f48f
