### ISSUE TITLE
Public Test Animation (and other) bugs

### ISSUE THREAD

**Issue by Mach131** [HouraiTeahouse/FantasyCrescendo#65]
-Youmu sometimes stays in her idle animation while jumping, apparently when the jump is performed during the landing animation.
-Similarly, jumping immediately after regrabbing the ledge leaves you in the ledgegrab animation until you jump again.
-If you walk off of the stage or a platform, you still get two jumps.
-The platform you respawn on is solid from all directions, even after you leave it.
-The stock count doesn't change when you die.

**Comment by james7132** [comment]
Stock count display should be updated upon death now.

**Comment by james7132** [comment]
Idle animation upon jumping and ledge grabs should be fixed now.

**Comment by james7132** [comment]
The animation issues should be fixed as of now. If the issues persist in the latest test build, please reopen this issue.
