### ISSUE TITLE
Camera gets weird angle when a player runs out of stock

### ISSUE THREAD

**Issue by Sombres9** [HouraiTeahouse/FantasyCrescendo#68]
Just by playing in any way, if you die enough times that the player ends up running out of stock, the game leaves the marker for the player where they died, and then the camera gets stuck trying to put all the players in camera, but also it can even end up zooming in.

![captura de tela 2017-02-01 22 47 37](https://cloud.githubusercontent.com/assets/25494553/22532853/4cdf94e2-e8d1-11e6-8776-860e45d7dd61.png)

![captura de tela 2017-02-01 22 55 32](https://cloud.githubusercontent.com/assets/25494553/22532893/9531dfb6-e8d1-11e6-93e3-199b0fa21554.png)

**Comment by james7132** [comment]
Unable to replicate in latest test build, can you please test again for the exact conditions in which it triggered?

**Comment by Sombres9** [comment]
Youmu cannot die in Forest of Magic in the latest build, so I cannot make her run out of lives to attempt to reproduce this.

**Comment by james7132** [comment]
Latest build should now support it. Can you attempt again?

**Comment by Sombres9** [comment]
Still cannot die and lose stock as Youmu. Playing on latest test build where mushrooms have been lowered.

**Comment by james7132** [comment]
As discussed on Discord, this has been effectively fixed as of the latest build. Can still happen due to non-deterministic results, however it shouldn't be possible in the end version of the game.
