### ISSUE TITLE
Clicking create internet match in rapid succession might create multiple players

### ISSUE THREAD

**Issue by Sombres9** [HouraiTeahouse/FantasyCrescendo#69]
This usually happens by simply opening the game, enabling matchmaker and clicking "create internet match" rapidly, causing multiple youmus to appear. You can make up to 4 Youmu/could appear to be 5 spawn, where all of them are controlled by you. 

If you click too much, one of the Youmus also spawns with a different skin, though it changes back to her green outfit after one death.

http://imgur.com/a/PlQEC

**Comment by james7132** [comment]
This should generally fix the replication bug. However, realistically this shouldn't be needed as we won't allow users to make a match creation request repeatedly.
