### ISSUE TITLE
Choosing the design of the main screens

### ISSUE THREAD

**Issue by KazeSenshi** [HouraiTeahouse/FantasyCrescendo#7]
Hello guys, while studying to learn more about the new Unity's UI system I made the following screens based on the original Super Smash Bros, including [screen transition animations](http://docs.unity3d.com/Manual/HOWTO-UIScreenTransition.html), [hand cursors controlled by the keyboard](http://forum.unity3d.com/threads/how-to-create-a-mouse-like-cursor-to-be-controlled-by-the-keyboard-or-a-joystick.299656/#post-1985155), a [mediator element](http://forum.unity3d.com/threads/looking-for-tips-about-implementation-of-mediator-design-pattern-in-c.299863/#post-1977216) to control the communication between the UI elements and internal data and a lot of bugs. Do you guys have other concepts or ideas to the main screens ( the main menu and the character selection screen )?

![menu1](https://cloud.githubusercontent.com/assets/11096942/6405130/840259c8-bdfe-11e4-8df1-be6109df1669.jpg)
Main menu, simple and straight with giant buttons.

![menu2](https://cloud.githubusercontent.com/assets/11096942/6405173/03e64032-bdff-11e4-906f-d52ed0df0ac3.jpg)
Character seleciton menu

![menu3](https://cloud.githubusercontent.com/assets/11096942/6405176/0c8773d2-bdff-11e4-827d-8c41725f09f0.jpg)
Player slots with Player, CPUs or empty

![menu4](https://cloud.githubusercontent.com/assets/11096942/6405186/22956896-bdff-11e4-87bd-42b656aef1ff.jpg)
Battle dropdown options

![menu5](https://cloud.githubusercontent.com/assets/11096942/6405188/2c1dc2dc-bdff-11e4-8e27-e91a4c87d13f.jpg)
Dropdown to choose CPU's intelligence level

**Comment by GandWuser** [comment]
Important things big. Lesser things small.

**Comment by GandWuser** [comment]
Also needs a random button. If ****** is a secret she should go next to it in the middle columns third row.

**Comment by KazeSenshi** [comment]
Hmmm I forgot the Random one... :P

Anyway what do you think that would look better bigger or smaller?

**Comment by GandWuser** [comment]
Make the player section bigger, make the character selection boxes smaller (just a tiny bit though), make the "Brawl" box slightly larger, make the "Back" slightly smaller. Also I'm not sure how likely a five-player set-up is going to work out since the standard is 4, but I guess we should discuss it.

**Comment by KazeSenshi** [comment]
Later I'll try to upload a new picture with your suggestions. Really I need to reduce a bit the character selection boxes to have space to show that "Press to start" strip when all players are ready to Smash.

The number of players is a variable, I chose 5 just because I didn't make the player slot's width dynamic yet and it looked better with 5 players.

**Comment by KazeSenshi** [comment]
Here is a new mockup pic with some modifications, I removed Keine for while to put random there. What do you think?
![indexx](https://cloud.githubusercontent.com/assets/11096942/6422799/8e07fac8-bebb-11e4-81da-ec00abac09fd.jpg)

**Comment by GandWuser** [comment]
Looks better. You probably could shrink the boxes a bit to let Keine get back on (and ****** would fill the other spot of course).

**Comment by KazeSenshi** [comment]
Well I'll let them confirm the character list before changing more the size of the boxes there because I saw 2 different lists in this github. If more people are OK with this layout them we could start to get some artists to generate the UI art to replace those white transparent images used in each element there. Or I could create them but I am not the best artist :P

**Comment by james7132** [comment]
For now, the only absolutely confirmed character is Reimu. Until we actually start on development of multiple characters, it would be best not to assume the roster to be a certain size.

I know next to nothing about the new uGUI system, but it should allow for dynamic additions of elements. How difficulty would it be to make a script that would it be to resize and move individual character slots given a list of them? If it is too much, we can defer that functionality til later.

**Comment by KazeSenshi** [comment]
I think that it isn't hard to change the elements to work with dynamic additions. The list is already dynamic, it only needs to control each slot's size too.

![index](https://cloud.githubusercontent.com/assets/11096942/6428758/c07fd644-bf8b-11e4-90a1-e7ac9871da7d.jpg)
By the way here is the Stage Menu like the one from Wii. When you hover over the stages it shows the stage's name, logo and image in the left side. When you click on any of them it should go to the battle sending the data from selected characters and stages.
