### ISSUE TITLE
Stage geometry of forest of magic causing wired interactions

### ISSUE THREAD

**Issue by HanedTom** [HouraiTeahouse/FantasyCrescendo#75]
![screenshot-03-13-2017-010108](https://cloud.githubusercontent.com/assets/25497816/23838101/da467a1a-075f-11e7-9a23-31fb6eb2e20c.png)
can stand right there with no hindrance
![screenshot-03-13-2017-010046](https://cloud.githubusercontent.com/assets/25497816/23838111/ed84eb52-075f-11e7-82c7-d194ed04aeb8.png)
also can stand here due to no ledges being implemented

**Comment by HanedTom** [comment]
and more weird interactions
![screenshot-03-13-2017-011411](https://cloud.githubusercontent.com/assets/25497816/23838197/0789c5ee-0761-11e7-9750-c5a1fb0b8cc3.png)
Can stand here can't come back on the stage but I can stand here
![screenshot-03-13-2017-011433](https://cloud.githubusercontent.com/assets/25497816/23838209/224c65d0-0761-11e7-86c8-2985001bb4e5.png)
as well as here and a place slightly below it.... might need to smooth the geometry or put invisible walls to prevent this silliness

**Comment by james7132** [comment]
This should be largely resolved in e0076bbd0337c887f619464267a376e8f8bab726. If the same problems persist, reopen this issue.
