### ISSUE TITLE
Youmu - double jump sometimes doesn't animate properly

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#79]
During the duration of Youmu's first jump, when the jump button is pressed, sometimes Youmu gets stuck in her falling animation while ascending in height.

**Comment by pzhang87** [comment]
Did we ever decide how to do the VFX for the double jump?  Including something basic might help with visual clarity in diagnosing this issue.

**Comment by james7132** [comment]
We have a single sprite for it, but no solid animation yet. I can just have it appear and fade over time.

**Comment by james7132** [comment]
Fixed. @pzhang87 can you create a separate issue regarding Jump visual effects?
