### ISSUE TITLE
Myon too Bright, bleaches out characters and background

### ISSUE THREAD

**Issue by magus0** [HouraiTeahouse/FantasyCrescendo#81]
It is hard to see when moving Youmu as Myon becomes much more bright. When facing right, will block out character model which does not allow players to see what moves are happening.

http://imgur.com/u29hl8X.jpg

http://i.imgur.com/1VsHRb9.jpg

**Comment by james7132** [comment]
Basic look and feel are complete as of #100. There is an introduced problem with the jagged tail of Myon, but that should be fixed when #97 is resolved.
