### ISSUE TITLE
Characters can crouch into movements directly without an idle in between.

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#83]
Running and crouching at the same time on sides of mushrooms creates weird animation transition.

https://youtu.be/BD4gK4zuhjQ

Left side of right mushroom can be run across since it's sloped - not sure if intentional, but it does make it a little weird.

**Comment by james7132** [comment]
Running and crouching shouldn't be possible period.

**Comment by james7132** [comment]
This should be resolved as of 0ae4a5bdf4c4263b4a153e08399c4efef005ae3d

**Comment by james7132** [comment]
Marking this as done. The issue in particular has been resolved.
