### ISSUE TITLE
Input biases when making inputs for simultaneous walking/running exist

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#85]
When walking left (left arrow key input) you can interrupt the walk with a run right (simultaneous D key input).  Similarly when dashing left (A key input) you can interrupt with a walk left (simultaneous right arrow key input).

The converse is not true - a walk right cannot be interrupted with a simultaneous dash left; a dash right cannot be interrupted with a simultaneous walk left.  

This is probably a subissue of a bigger issue that needs to be resolved when looking at the input controller, maybe a revisit to character states as well.

**Comment by james7132** [comment]
Resolved as of 60f4f3f8f8998ec77d5dccb0b75c54f9927fda5e
