### ISSUE TITLE
Flesh out character states (planning/discussion)

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#86]
From playtesting, we're missing some character states that we need to implement to smooth out transitions between what we have already.  For instance, when Youmu lands, she lands on her feet (doesn't enter a landing squat) and can dash/jump instantly.  This can create some strange animations:

https://youtu.be/n3LlUeOAFWQ

A cursory look at this thread (https://smashboards.com/threads/list-of-all-possible-character-states-ie-downdamage-downwait.400270/#post-19055623) shows that we're missing a quite few, though we don't need to implement all of these for our MVP.

This issue will serve as a discussion thread for how we should go about doing this.

**Comment by james7132** [comment]
I initially though we could handle this via Unity's blend engine, but clearly this introduces some very bizarre transitions.

We should go through this list sometime soon and evaluate:

1. What each state is for
0. Do we need it for our MVP.
0. Do we need a separate animation for
0. The approximate timings for Youmu.

We may need to redo this evaluation with each character we work on as well.

**Comment by james7132** [comment]
An enumeration of all of the states and their relevance to this project can be found here: https://docs.google.com/spreadsheets/d/1c_CoyGlBVoNRgk5H0HfqykVPadnDCb2CeXpAPJ3RWJE/edit?usp=sharing

**Comment by james7132** [comment]
These have been implemented and completed as of 0ae4a5bdf4c4263b4a153e08399c4efef005ae3d
