### ISSUE TITLE
Youmu - jump/landing squat states + animations

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#87]
We need to add in a transition state from grounded (standing/walking/dashing) to jumping for each character, as well as from falling to grounded.  This helps with animation flow and introduces a delay on player actions.  This is useful, because otherwise we can end up with this:

https://youtu.be/n3LlUeOAFWQ

Here, Youmu can basically dash/jump as soon as she lands, which looks pretty bizarre if the player just focuses on doing this.

Jump squat durations are very short (i.e. 4frames or ~67ms), landing squat durations are longer and can vary based on whether or not a character has attacked.  I think for a starting point, we can potentially repurpose the crouch animation for the MVP and see how we need to refine further later.

**Comment by james7132** [comment]
There now exists JumpStart and Land states separate from the respective states as of 0ae4a5bdf4c4263b4a153e08399c4efef005ae3d. Seperate animations have been added for Land but the transitions don't seem to work as intended. Small bug fixes may be needed.
