### ISSUE TITLE
research custom animation system

### ISSUE THREAD

**Issue by pzhang87** [HouraiTeahouse/FantasyCrescendo#99]
Relates to #86.  Need to figure out how to adapt/modify or rewrite Unity's native animation system so we can have better control of state transitions.

**Comment by james7132** [comment]
https://docs.unity3d.com/Manual/Playables.html

**Comment by james7132** [comment]
A tentative state controller that is capable of directly controlling animation is implemented as of 0ae4a5bdf4c4263b4a153e08399c4efef005ae3d. It seems to work decently well, but needs more work to smooth out the kinks.
